author not appearing in citation when using roleTerm marcrelator codes
Islandora/islandora_scholar pull request #244
Opened 2016-10-14 22:38 UTC by jefferya

**JIRA Ticket**: (https://jira.duraspace.org/browse/ISLANDORA-1829)

https://groups.google.com/forum/#!topic/islandora/NNnzrSaay14

# What does this Pull Request do?

Author name not appearing within the citation with using roleTerm marcrelator codes

# What's new?

As discussed in the Google Group, issue appears to be due to a global variable scoping oversight. Code added to rectify scoping problem.

# How should this be tested?

JIRA Ticket includes a sample MODS record.

Two cases to test include MODS records of the form:

Broken - no author in CSL citation
–
<role>
<roleTerm type="code" authority="marcrelator">aut</roleTerm>
</role>
Broken - no author in CSL citation
–
<role>
<roleTerm type="code" authority="marcrelator">aut</roleTerm>
<roleTerm authority="marcrelator" type="text">Author</roleTerm>
</role>

# Additional Notes:

# Interested parties
@DiegoPino

2016-10-14 23:00 UTC, DiegoPino commented
@jefferya thanks! Just to be sure(and excuse me if i'm wrong, i just don't know where you work), are you/or your Institution covered by a Contributor Licence Agreement? If not please submit one to @manez, more instructions [here] (https://github.com/Islandora/islandora/wiki/Contributor-License-Agreements). Once that is solved i will review your pull 👍

2016-10-20 20:10 UTC, DiegoPino requested changes

2016-10-20 20:10 UTC, DiegoPino commented on modules/citeproc/includes/marcrelator_conversion.inc
> +global $_ir_citation_marcrelator_codes;
@jefferya there is a whitespace at the end of this line. That makes phpcs fail on travis.

2016-11-02 17:30 UTC, jefferya commented
@DiegoPino I've e-mailed a Contributor License Agreement to community@islandora.ca.

2016-11-02 17:35 UTC, DiegoPino commented
@jefferya thanks for that! Will wait for @manez to update the info and will merge. great!

2016-11-02 17:44 UTC, manez commented
I have @jefferya 's iCLA on file. May want to wait for his confirmation that he doesn't need a cCLA as well, but otherwise 👍

2016-11-02 18:09 UTC, DiegoPino commented
@manez thanks. Will wait then until i get that confirmation!

2016-11-04 16:45 UTC, manez commented
@jefferya @DiegoPino all set on the cCLA front as well!

2016-11-04 17:19 UTC, DiegoPino approved these changes

2016-11-04 17:19 UTC, merged

2016-11-04 17:20 UTC, DiegoPino commented
@jefferya congrats on your first merged pull request on islandora! Looking forward your next one =)